### ISSUE TITLE
production vs development

### ISSUE THREAD

**Issue by vitormsilva** [reTHINK-project/dev-runtime-browser#46] opened 2016-05-19 10:40 UTC
Hi @dvilchez,

in the runtime-browser the choose between development and production isn't distinguish
```
rethink.install({
    "development": false,
    "runtimeURL": "hyperty-catalogue://catalogue.hybroker.rethink.ptinovacao.pt/.well-known/runtime/Runtime",
    "domain": "hybroker.rethink.ptinovacao.pt"
  })
```
But the runtime-browser always transform the request to `hyperty-catalogue://catalogue.hybroker.rethink.ptinovacao.pt/resources/descriptors/Runtimes.json` and shouldn't.

Regarding the specification:
- Local Catalogue (development = true):
**hyperty-catalogue://hybroker.rethink.ptinovacao.pt/resources/descriptors/Runtimes.json`**

- Catalogue  (development = false):
**hyperty-catalogue://catalogue.hybroker.rethink.ptinovacao.pt/.well-known/runtime/Runtime`**

**Comment by dvilchez** [comment] 2016-05-20 08:39
@vitormsilva I think it is a little more complex...
here are the specifications

https://github.com/reTHINK-project/dev-runtime-browser/blob/master/test/RuntimeUAStub.spec.js

Please get an agreement with @pchainho and tell me what I have to change

**Comment by vitormsilva** [comment] 2016-05-20 10:11
I think haven't nothing to agree with @pchainho, because the problem is, as you see before, I'm passing the domain like `hybroker.rethink.ptinovacao.pt` and the request to get the iframe (index.html) add the `catalogue` like this `https://catalogue.hybroker.rethink.ptinovacao.pt/.well-known/runtime/index.html` and this URL doesn't exists

**Comment by dvilchez** [comment] 2016-05-20 10:27
Ok @vitormsilva, I remember now,

as you can see the line is commented because it didn't work at that moment.

https://github.com/reTHINK-project/dev-runtime-browser/blob/master/src/RuntimeUAStub.js#L74

Anyway, it is not supposed you are going to pass to the method both parameters. If you do it, runtimeURL will keep its value.

**Comment by pchainho** [comment] 2016-05-25 11:31
what is the status of this issue?

We have to close this asap to have the browser runtime integrated in the toolkit and have a new release

**Comment by dvilchez** [comment] 2016-05-27 11:36
@pchainho I couldn't reproduce the error but I was debugging this with @vitormsilva and I know nothing more since then

**Comment by pchainho** [comment] 2016-05-27 12:06
Does it mean you are able to use the Catalogue from Fokus in production mode ie development = false?

**Comment by dvilchez** [comment] 2016-05-27 13:07
@pchainho I never try it but I can resolve runtimeCatalogue or runtimeCatalog-local based on the configuration

**Comment by pchainho** [comment] 2016-05-27 16:46
In our tests the browser runtime in production mode is using an incorrect URL to download rethink.js.

But @dvilchez says it is using the correct URL ie  `https://hybroker.rethink.ptinovacao.pt/.well-known/runtime/rethink.js`

Further debug is needed to understand what is wrong ...

**Comment by vitormsilva** [comment] 2016-05-30 16:35
Hi @dvilchez,

I'm trying to debug what is the problem, and I did some console.logs to your code, and I found this.

![screenshot from 2016-05-30 17-26-57](https://cloud.githubusercontent.com/assets/10596749/15654465/6a9420c8-268c-11e6-879f-4d32eccd1b0f.png)

The parameters are false, but in the `core.js` file is converted to  true;

**Closed** 2016-05-31 06:34 UTC
Labels: in progress
